### ISSUE TITLE
Viewing Previous Orders

### ISSUE THREAD

**Issue by zakisaad** [lsretailomni/lsmag-two#10]
Hi -

Do customers have the ability to view past (imported) orders - for example from pre-LS Magento - when this plugin is installed?

Can only seem to get current customer orders displayed, no previous orders at all.

Is this expected?

**Comment by sudhanshu-bajaj** [comment]
Hi @zakisaad, 

If you mean the past orders in Magento (**before LS Ecommerce Magento installation**) then answer is No. But if customer Sales History exist in the LS Central/NAV then yes those will be visible in customer My Account section provided the Username is same.

Thanks

**Comment by zakisaad** [comment]
Hi @sudhanshu-bajaj 

Thanks for the response. We are considering to bring in all previous Magento orders into NAV as Posted Customer Orders (so that they are viewable in the order history tab).

Do you see any issue with us proceeding with the above data migration?

Or, would you advise for us instead to modify the LS_Customer module to switch and show both Magento-ONLY as well as LS linked orders (and leave the original orders out of NAV entirely).

TIA!

**Comment by sudhanshu-bajaj** [comment]
Hi @zakisaad,

I would recommend data migration to LS Central/NAV. It will be great in terms of maintainability of our extensions. 

Thanks

**Comment by zakisaad** [comment]
Hi @sudhanshu-bajaj 

Thanks for the insight, we will be migrating data in to our NAV/LS database.

Just FYI, we've been heavily modifying the LS Mag plugin to support our own use-cases. We now have the ability to sell simple products (with custom options) and bundle products (which sync from NAV Assembly BOMs), which then create Assembly Orders on the Customer Order linked Sales Order.

One thing we have noticed, the use of the "-" character to separate variants clashes with Magento's use of the "-" character to select SKUs for custom options on simple products - we've had to employ 

One quick question - what (approx) size item catalogue are the replication cron jobs tested with? My client has over 20k SKUs, so we are tweaking the batch sizes to suit - would be great to have some insight on these numbers.

TIA

**Comment by sudhanshu-bajaj** [comment]
Hi @zakisaad, 

We have improved our extensions quite a lot since our first release and we are committed to make it more better. 

Regarding the 20k SKUs we already have one customer LIVE in Iceland having the similar large catalog. So far things are going smooth. 

Please do share your story in terms of performance or any other insights.

Thanks

**Comment by zakisaad** [comment]
Hi @sudhanshu-bajaj -

Thanks for your follow-up here. We are finally live, and performance seems to be adequate (however, we are fighting fires all over the place - not specifically related to LS Mag 😅). 

One of many useful features we have added include the ability to "Push Order" back to NAV if the Omni order creation failed for whatever reason - on the Sales Order view page, we simply added a button to call the order creation code (and generate a generic OneList calculation based on the Mag order model). Without a few helpers like this, ongoing operations can slowed down quite a bit.

Are there official channels to discuss our general experience with this Go Live?

**Comment by sudhanshu-bajaj** [comment]
Hi @zakisaad,

Thank you for letting us know. Please drop a line [here](mailto:sudhanshu.b@lsretail.com). Let's take it from there.

**Comment by sudhanshu-bajaj** [comment]
> Hi @sudhanshu-bajaj -
> 
> Thanks for your follow-up here. We are finally live, and performance seems to be adequate (however, we are fighting fires all over the place - not specifically related to LS Mag 😅).
> 
> One of many useful features we have added include the ability to "Push Order" back to NAV if the Omni order creation failed for whatever reason - on the Sales Order view page, we simply added a button to call the order creation code (and generate a generic OneList calculation based on the Mag order model). Without a few helpers like this, ongoing operations can slowed down quite a bit.
> 
> Are there official channels to discuss our general experience with this Go Live?

Hi @zakisaad, We really want to know more about your experience. May I know what is your website URL ?

**Comment by zakisaad** [comment]
> > Hi @sudhanshu-bajaj -
> > Thanks for your follow-up here. We are finally live, and performance seems to be adequate (however, we are fighting fires all over the place - not specifically related to LS Mag 😅).
> > One of many useful features we have added include the ability to "Push Order" back to NAV if the Omni order creation failed for whatever reason - on the Sales Order view page, we simply added a button to call the order creation code (and generate a generic OneList calculation based on the Mag order model). Without a few helpers like this, ongoing operations can slowed down quite a bit.
> > Are there official channels to discuss our general experience with this Go Live?
> 
> Hi @zakisaad, We really want to know more about your experience. May I know what is your website URL ?

Hey @sudhanshu-bajaj - will follow up on your previously linked message! 😀

**Comment by zakisaadjw** [comment]
Hey @sudhanshu-bajaj -

Did you receive my email correspondence? There is a fairly critical issue we have just detected that should be escalated right to the Omni team.

Thanks -

**Comment by zakisaad** [comment]
Hi @sudhanshu-bajaj -

Did you get my email correspondence? There is a fairly critical issue we have just found that should be escalated right to the Omni team...

Thanks -

**Comment by sudhanshu-bajaj** [comment]
> Hi @sudhanshu-bajaj -
> 
> Did you get my email correspondence? There is a fairly critical issue we have just found that should be escalated right to the Omni team...
> 
> Thanks -

Hi @zakisaad,

I haven't got any email from you. Could you please try sending again ?

Thanks

**Comment by zakisaad** [comment]
Hi @sudhanshu-bajaj - I sent the email on the 2nd of April.

Will resend now - is your address still sudhanshu.b@lsretail.com?

**Comment by sudhanshu-bajaj** [comment]
> Hi @sudhanshu-bajaj - I sent the email on the 2nd of April.
> 
> Will resend now - is your address still [sudhanshu.b@lsretail.com](mailto:sudhanshu.b@lsretail.com)?

Yes, please.

**Comment by zakisaad** [comment]
I've followed up just now.

Thanks @sudhanshu-bajaj !
