### ISSUE TITLE
kiwicommerce/module-cron-scheduler should not be a hard requirement

### ISSUE THREAD

**Issue by hostep** [lsretailomni/lsmag-two#11]
Hi folks

I just got the assignment from one of our clients to install this module.
But by doing so, I was surprised to see the `kiwicommerce/module-cron-scheduler` being installed as well.

I quickly searched your code, and I'm not seeing anything making use of that module.
So I'm wondering what the reason was to make it a hard dependency?

Maybe you guys like that module, but be aware that there are multiple other modules out there which provide a very similar functionality. If a shop already has one installed and then installs your module, it would suddenly get a second cron scheduler module installed which they probably don't need and might even conflict with their previously installed one.
It should be up to the store owner to decide if and which cron scheduler module they install.
Other modules shouldn't try to push a particular cron schedule module, right?

I would propose to move the entry for `kiwicommerce/module-cron-scheduler` from the `require` section to the `suggest` section in the `composer.json` file. And maybe add some kind of notice to the readme file that you guys suggest people to install that module.

Thoughts?

Thanks!

**Comment by sudhanshu-bajaj** [comment]
Hi @hostep,

Thanks for sharing you suggestion. Since we have very hard dependency on CRONs, this module is good to have. But we will discuss internally and take action accordingly for new release.

Thanks,
Sud

**Comment by hostep** [comment]
Hi @lsretailomni 

Why did you close this issue? I don't see that module being removed yet in the 1.3.0 release, so there is no reason to close this ticket without some explanation.

I will continue my argument though: the module might have a strong dependency on crons, but it has no strong dependency on any visualisation tool to make the crons better visible in the backend of Magento. So it should **not** have a dependency on `kiwicommerce/module-cron-scheduler` in the `composer.json` file.
I agree the `kiwicommerce/module-cron-scheduler` module is good to have if you have the lsretail module, but other cron-visualiser modules can be a good alternative. You guys shouldn't shove this `kiwicommerce/module-cron-scheduler` down our throats if we have other alternatives for it already installed, this is a choice the system integrator or shopowner has to make, you really don't have to make this choice for us.

Like suggested, you should move `kiwicommerce/module-cron-scheduler` from the `require` to the `suggest` section in the  `composer.json` file and add a recommendation in your README file for people that you highly recommend to install this module.

Please re-open the issue, thanks!

**Comment by hostep** [comment]
Looks like this was fixed in version 1.3.1 by https://github.com/lsretailomni/lsmag-two/commit/7ae7f004a784e18b118c767a8afdd5011b20641a

Thanks guys!
