### ISSUE TITLE
UnitCost sql errors

### ISSUE THREAD

**Issue by hostep** [lsretailomni/lsmag-two#14]
### Preconditions (*)
1. Magento: OS 2.3.4
2. LS Central version: unknown
3. LS Omni version: unknown
4. LS eCommerce - Magento version: 1.3.0

### Steps to reproduce (*)
1. In the backend of Magento, go to LS Retail > Replication Status > Item
2. Click the column 'Unit Cost' to sort on that column

### Expected result (*)
1. Either not seeing that column, or if it is actually needed, having the filter action not crash the grid

### Actual result (*)
1. Getting an error "Something went wrong with processing the default view and we have restored the filter to its original state."
2. In the `var/log/exception.log` file seeing the error:
```
main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UnitCost' in 'order clause', query was: SELECT `main_table`.* FROM `ls_replication_repl_item` AS `main_table` ORDER BY UnitCost ASC
```

### Discussion
Since the column `UnitCost` does not exist in the table `ls_replication_repl_item`, you should probably remove that column from the ui component grid (and maybe double check if no other columns are incorrectly defined there)

**Comment by lsretailomni** [comment]
@hostep Thank you for reporting the issue. We have added to our backlog.
