### ISSUE TITLE
Inventory status Replication Issue 

### ISSUE THREAD

**Issue by EngPeterMaged** [lsretailomni/lsmag-two#16]
### Preconditions (*)

1. Magento V2.3.3
2-Ls Retail Magento 2 Extension
3.  Omni Server 4.2
4. LS Central 14.1

### Steps to reproduce (*)

1. Configure Ls Retail Module to my Omni server
2. php bin/magento cron:run
3. Wait to Results

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1.  I have all Products With Quantity 0 .
![image](https://user-images.githubusercontent.com/57891823/84039540-a9186b00-a9a1-11ea-97f3-7e36075f2a1a.png)

2-  all Replicated data with inventory with quantity 0 
![image](https://user-images.githubusercontent.com/57891823/84039602-c6e5d000-a9a1-11ea-9d75-0e2afe587aeb.png)

there is my Ls Retail Configuration.
![image](https://user-images.githubusercontent.com/57891823/84039391-77070900-a9a1-11ea-819f-f35a7dda7b75.png)

what should i do to Replicate All Product With Its Quantities in inventory Successfully.

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

Please follow the steps:

**From LS Central** 
- Make sure your configured Web Store have inventory available.
- After updating the inventory, please run the OMNI_INVENTORY job under **SCHEDULER JOB LIST**.

**From Magento Admin**
- Go to LS Retail > Manual Crons > Cron Listing.
- Click Execute next to '_repl_inv_status_reset_' cron job and then
- Click Execute next to '_repl_inventory_sync_' cron job

Please let us know if you still facing the issue.

If you're LS Retail active partners you can use **LS Partner & Customer Portal** to submit the technical support request. 

- Partner Portal: https://portal.lsretail.com/
- support@lsretail.com

Thanks,
Team LS eCommerce - Magento

**Comment by EngPeterMaged** [comment]
thanks it is working for me
