### ISSUE TITLE
Create new Account Problem not Synched with Ls Bussines Central 14

### ISSUE THREAD

**Issue by EngPeterMaged** [lsretailomni/lsmag-two#17]
when i creating new account from magento i cant find it in Ls central member contacts and i cant make new order in checkout page it is give me a loading Image for long time .

### Preconditions (*)

1.Magento V2.3.3
2-Ls Retail Magento 2 Extension 1.3.1
3.Omni Server 4.2
4.LS Central 14.1

### Steps to reproduce (*)

1. Create new Account in magento
2. Go to Member Contact in Ls Central
3. Search for my Contact
4. try to goto checkout page and place order.

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/57891823/84248966-6f16a880-ab0a-11ea-8848-580c1d891c12.png)

![image](https://user-images.githubusercontent.com/57891823/84248775-32e34800-ab0a-11ea-8393-e5676f27072a.png)

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

We need more details to debug the issue. Please share the details via support ticket.

Also could you please double confirm Omni Service is working ? Or may be **Omniclient.log** have some details for this. 

If you're LS Retail active partners you can use LS Partner & Customer Portal to submit the technical support request.

- Partner Portal: https://portal.lsretail.com/
- support@lsretail.com

Thanks,
Team LS eCommerce - Magento

**Comment by EngPeterMaged** [comment]
when create new customer account in magento it will be create in magento Accounts only   it didn't create a new member contact in LS Central

**Comment by EngPeterMaged** [comment]
Expected result  is when creating new account in magento then will be a new member contact in LS Central Member Contacts with same data

**Comment by EngPeterMaged** [comment]
"LS eCommerce - Magento enables member registration through Magento."
is not working for me

**Comment by EngPeterMaged** [comment]
all omni function is working properly 
in login is working fine but its n't working in Register new account

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

We need to refer omni log for this. Could you please share with us?

Thanks,
Team LS eCommerce - Magento

**Comment by EngPeterMaged** [comment]
[omniclient.log](https://github.com/lsretailomni/lsmag-two/files/4764214/omniclient.log)

**Comment by EngPeterMaged** [comment]
my LS Central version is 14.0 
My omni version is 4.2 
my LS Mag version is 1.3.1
My Magento version is 2.3.3

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged, 

Unfortunately, we don't see any **ContactCreate** method request and response in the Omniclient.log. Maybe you can verify method using API test tool first. If it works there then we sure something wrong at LS eCommerce - Magento side then we might need your Magento instance access to debug further.

We are calling ContactCreate method in Magento for creating member account, please refer [here](http://mobiledemo.lsretail.com/LSOmniHelp/html/M_LSOmni_Service_IUCService_ContactCreate.htm) for example.  You can use [SoupUI tool](https://www.soapui.org/) to verify.

Also we highly recommend to install Omni 4.8.

Hope this is helpful.

Thanks

**Comment by EngPeterMaged** [comment]
yes it is my proplem it is n't calling ContactCreate  Function after create new account in magento , how to solve or debug this issue .

**Comment by EngPeterMaged** [comment]
Hi Ls Retail

thanks for your reply and support,
My omni server is work correctly and iam test it from Postman
omni version : 4.2
LSMAG extension is 1.3.1
Magento : 2.3.3
LS central : 14.0
this My server Cardinality

VPN configuration
Remote Gateway : 196.219.232.90
Port : 4433
username : eadly
password : 123456

omni server url : http://197.51.15.83/LSOmniservice/ucjson.svc

magento server
IP :  10.0.1.26
username : root
password : Aa123456

magento path : /opt/lampp/htdocs/magento
Magento URL : http://magento2.linkedgates.com/magento/
Magento Admin URL : http://magento2.linkedgates.com/magento/admin_194jxt
<http://magento2.linkedgates.com/magento/>
admin username : Peter
admin Password : LinkedGates@2021

Please support me in this issue
thanks in advance.

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

Thanks for providing the details. We will get back to you ASAP.

Thanks,
Team LS eCommerce - Magento

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

We are not able to connect to the VPN. Seems certification is missing.

Maybe you can drop an email [here](mailto:sudhanshu.b@lsretial.com).

Thanks,
Team LS eCommerce - Magento

**Comment by EngPeterMaged** [comment]
eng.peter.maged@gmail.com

**Comment by EngPeterMaged** [comment]
how to debug the LS Retail Extension

**Comment by lsretailomni** [comment]
Issue because of register.phtml template was overwritten by third party module. Closing issue now.
