### ISSUE TITLE
Stores Page Error

### ISSUE THREAD

**Issue by EngPeterMaged** [lsretailomni/lsmag-two#18]
### Preconditions (*)

1.Magento V2.3.3
2-Ls Retail Magento 2 Extension 1.3.1
3.Omni Server 4.2
4.LS Central 14.0

### Steps to reproduce (*)

1. Go to stores Page in  Home Page 
2.<Magento Link >/omni/stores 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

![image](https://user-images.githubusercontent.com/57891823/84371209-95efe000-abd9-11ea-8386-fce33d6bb874.png)

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

This object doesn't exist in your Omni version. Could you please update the Omni Server to latest version ? This should solve the problem.

Please refer [compatibility here](https://github.com/lsretailomni/lsmag-two#compatibility). 

Thanks
