### ISSUE TITLE
I have error when Creating Member Contact In First Time

### ISSUE THREAD

**Issue by EngPeterMaged** [lsretailomni/lsmag-two#19]
### Preconditions (*)

1. LS Central 14.0.2
2.  Ls Omni Server 4.8
3. Magento 2.3.3 
4. LS magento Extension 13.2

### Steps to reproduce (*)

1. When i create Contact i have this error 
how to solve it .?
![2020-06-18](https://user-images.githubusercontent.com/57891823/85053499-e0a1c700-b19a-11ea-80c5-0ff9cdc23135.png)

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by lsretailomni** [comment]
Hi @EngPeterMaged,

Closing this issue, as you were able to fix this after updating the modules.

Thanks
