### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by anhtuantl** [lsretailomni/lsmag-two#2]
Dear Team,

I haved a isssue when i compiled detail in below. 

PS D:\xampp\htdocs\Magento226> php bin/magento setup:di:compile
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 52.0 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 52.0 MiBProxies code generation... 0/7 [>---------------------------]   0% < 1 sec 52.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 2 secs 54.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 54.0 MiB

  [RuntimeException]
  Source class "\Ls\Replication\Model\ReplImageLinkInterface" for "Ls\Replication\Model\ReplImageLinkRepository" gene
  ration does not exist.
setup:di:compile

Thanks
Tuan

**Comment by lsretailomni** [comment]
thanks for reporting @anhtuantl , you need to setup the base url of omni server from the shell command and test the connection to your omni server.

To set the base url of omni server from command line, you can run this command:

` php bin/magento config:set ls_mag/service/base_url http://yourOmnihostname/LSOmniService`

after you setup your omni server url, you can use this command to see if connection to your omni server is built successfully or not. To do so you can run

`php bin/magento omni:client:ping`

once the connection is built successfully you can run below commands to generate all the files for replication which magento need from omni

```
php bin/magento omni:client:generate

php bin/magento replication:generate 
```
