### ISSUE TITLE
ContactCreate Operation validation 

### ISSUE THREAD

**Issue by EngPeterMaged** [lsretailomni/lsmag-two#20]
### Preconditions (*)

1. magento 2.3.3
2. Ls Omni 4.8
3. LS Central 14.0.2
4. LS mag extension 1.3.2

### Steps to reproduce (*)

1. Create new account with same mail or username exist on Ls central Member Contacts but not exist in Magento Customers
2. the account will created successfully on magento but will be not created on LS Central
3.  need to show any error occurs on omni server  in magento Screen

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by lsretailomni** [comment]
Closing this issue. Had a call with customer on how to handle the errors.

Thanks,
Team LS eCommerce - Magento
