### ISSUE TITLE
Version 1.4.1 contains no changes compared to 1.4.0

### ISSUE THREAD

**Issue by hostep** [lsretailomni/lsmag-two#26]
Hi guys

It looks like you released version 1.4.1 of your module without any changes in the code: https://github.com/lsretailomni/lsmag-two/compare/refs/tags/1.4.0...refs/tags/1.4.1 ?

Even though the changes in the changelog claims that 3 fixes were done in scope of 1.4.1

So this is a bit confusing?
Was a mistake made here or what is happening with these versions exactly?

Thanks!

**Comment by lsretailomni** [comment]
Hi @hostep,

Thank you for your feedback. We have already merged the 3 fixes in Version 1.4.0. Nevertheless, we have to release new version to keep our package version upto date. 

We will take care next time. Sorry for confusion.

Thanks,
Team LS eCommerce - Magento

**Comment by hostep** [comment]
This makes no sense 😛 

If the 3 fixes were already in 1.4.0, why then create a version 1.4.1 where you claim you've fixed those 3 issues?

**Comment by lsretailomni** [comment]
Hi @hostep,

Last week we released the 1.4.0 but we found few hot fixes which required immediate action, so we pushed changes to the same tag. Due to package cache some of our customers were not able to get the latest version, therefore we had to release the new version.

Thanks for your cooperation.

**Comment by hostep** [comment]
Aaah, that explains!

Please don't ever do that again, always generate new versions for hotfixes in the future, never re-use an already published version.

Thanks for the feedback though, let's close this issue.
