### ISSUE TITLE
Avoid using core block reference name within core layout scope

### ISSUE THREAD

**Issue by sohelrana09** [lsretailomni/lsmag-two#27]
### Preconditions (*)

1. Magento OS 2.4.0
2. LS Central: no idea
3. LS Omni: no idea
4. LS eCommerce - Magento: 1.6.1

### Steps to reproduce (*)

1. Use a reference block of **order_additional_info** which is the core block name in the layout **adminhtml/layout/sales_order_view.xml**. Ex. layout code:
<pre><code>&lt;?xml version="1.0"?>
&lt;page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    &lt;body>
        &lt;referenceBlock name="order_additional_info">
            &lt;block class="VendorName\ModuleName\Block\Adminhtml\Order\View\TestBlock"
                   name="sales_order_test_block_info"
                   template="LittleFarms_Checkout::sales/order/view/test-block.phtml" />
        &lt;/referenceBlock>
    &lt;/body>
&lt;/page>
</code></pre>
2. Go to admin sales order view page
3. You can't able to see the new custom block.

### Expected result (*)

1. Anyone can use that block as a reference and add a custom block in the admin sales order view page because that is how magento allow to adding a custom block in the sales order view page instead of overwriting the whole phtml template file.

### Actual result (*)

1. Doesn't work after enable this LS Magento connector module. Because one of the block names used exactly the same as the core.

### Discussion
You need to avoid using exactly the same block name in your core customization. Here is an example of why that happened:

Filename: vendor/lsretail/lsmag-two/src/Omni/view/adminhtml/layout/sales_order_view.xml
<pre><code>&lt;referenceBlock name="order_info">
        &lt;block class="Magento\Sales\Block\Adminhtml\Order\View\Info" name="order_additional_info"
               template="Ls_Omni::order/view/additional-info.phtml" after="-"/>
    &lt;/referenceBlock></code></pre>

Please avoid using order_additional_info. You can rename this by ls_order_additional_info.

**Comment by lsretailomni** [comment]
Hi @sohelrana09 , thanks for reporting, we have added this in our backlog and will be available in our next release.

**Comment by zeeshan2523806** [comment]
@sohelrana09 this has been fixed in https://github.com/lsretailomni/lsmag-two/commit/43515c617bcf5e634a30e87da0dd2cd80a6ee0b8 and is already published in latest release. closing this.
