### ISSUE TITLE
Orders without shipping address cannot be send to LS retail because it expects a shipping address. 

### ISSUE THREAD

**Issue by duckchip** [lsretailomni/lsmag-two#30]
### Preconditions (*)

1. Magento 2.3.5
2. lsretail 1.6.1

### Steps to reproduce (*)

1. Buy a downloadable product (which don't have a shipping address) for example a gift card
2. Try to sync the order to ls Retail in the back-office on the order detail page
3. 

### Expected result (*)

1. Order is synced

### Actual result (*)

1. white page, 500 error

**Comment by lsretailomni** [comment]
This has been fixed in https://github.com/lsretailomni/lsmag-two/pull/31, closing this.
