### ISSUE TITLE
Using the shippingAdditional section in checkout_index_index removes other extra components

### ISSUE THREAD

**Issue by duckchip** [lsretailomni/lsmag-two#32]
### Preconditions (*)

1.  all magento versions
2.  all ls retail versions

### Steps to reproduce (*)

1. Install any magento version
2. Install ls retail module
3. add a custom module that also uses the shippingAdditional section in the checkout_index_index layout file. 

### Expected result (*)

1. see both components in the shippingAdditional section 

### Actual result (*)

1. only 1 component will be shown (depending on the order of modules)

### Possible solution
A fix for this is using the LayoutProcessor instead of using the checkout_index_index.xml file. I see that the ls retail module already has this in place so this change won't ask a lot of effort.

**Comment by lsretailomni** [comment]
This has been fixed in https://github.com/lsretailomni/lsmag-two/pull/33. closing this.
