### ISSUE TITLE
Issue with Membership Card information not sent to LS Central

### ISSUE THREAD

**Issue by Alex-The-Great-84** [lsretailomni/lsmag-two#36]
### Preconditions (*)

1. Magento - 2.4.0
2. LS Central - 16.3
3. LS Omni - 4.13 
4. Cactoz Pte Ltd

### Steps to reproduce (*)

1. Add item to cart as a guest
2. Login as a member
3. Item remain in cart, no further modification to the cart
4. Perform checkout as per normal 
5. Order was created without the membership card ID 

### Expected result (*)

1. Order should have been created with the membership card ID

### Actual result (*)

1. Order was created without the membership card ID

**Comment by lsretailomni** [comment]
Hi @AlexNgWeeLeong ,

Thanks for sharing the details, we have added it in our backlog and it will be available in our next release.

**Comment by lsretailomni** [comment]
@AlexNgWeeLeong this has been fixed and released in 1.9.0
