### ISSUE TITLE
Stopped processing Magento Native Sales Rules

### ISSUE THREAD

**Issue by sergii-zheleznytskyi** [lsretailomni/lsmag-two#37]
By writing a preference for this class you made not working Magento native Sales Rules Functionality.
Was that the idea of this module?
https://github.com/lsretailomni/lsmag-two/blob/da46c4b184f7add7a62c330103ea43f3ab26f36c/src/Omni/etc/di.xml#L43

**Comment by lsretailomni** [comment]
@sergii-zheleznytskyi all business logic including the sales rules needs to be defined in LS Central.
