### ISSUE TITLE
ProductCreateTask::caterItemsRemoval - productRepository->get not wrapped in a try-catch

### ISSUE THREAD

**Issue by henriksjodahl** [lsretailomni/lsmag-two#38]
We recently had a problem where we got a record in ls_replication_repl_item with "isDeleted" set to true. The problem being that the product with the SKU deleted didn't exist in Magento yet, resulting in ProductCreateTask crashing on the linked line. Wrapping the productRepository->get within the try-catch resolves that.

https://github.com/lsretailomni/lsmag-two/blob/10dcbe38013cab97c05fd187752bec1fc67d5dd2/src/Replication/Cron/ProductCreateTask.php#L1058

**Comment by lsretailomni** [comment]
Hey @henriksjodahl  , Thanks for reporting, this has been fixed in V2.0.0. Please see the changelog here: https://github.com/lsretailomni/lsmag-two/blob/master/CHANGELOG.md#bugsfixes
