### ISSUE TITLE
Unit tests are not passing

### ISSUE THREAD

**Issue by utrekstur** [lsretailomni/lsmag-two#39]
### Preconditions (*)
1.  Magento 2.4.3-p2, Magento 2.4.4-p1
2. LS Central version 14.99 - 18.00
3. Phpunit "phpunit/phpunit": "^9",
Company: Hagar

### Steps to reproduce (*)
1. ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml

### Expected result (*)
1. Unit tests should pass

### Actual result (*)
1. The same error for every unit test class 
PHP Fatal error:  Declaration of Ls\Omni\Test\Unit\Client\PingTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void

**Comment by lsretailomni** [comment]
Hey @utrekstur , Thanks for reporting, this has been fixed in V2.0.0. Please see the changelog here: https://github.com/lsretailomni/lsmag-two/blob/master/CHANGELOG.md#bugsfixes
