### ISSUE TITLE
missing translation function in template

### ISSUE THREAD

**Issue by utrekstur** [lsretailomni/lsmag-two#40]
Preconditions (*)
Magento 2.4.3-p2, Magento 2.4.4-p1
LS Central version 18.00
Company: Hagar

Steps to reproduce (*)
Ls/Customer/view/frontend/templates/order/totals.phtml

Expected result (*)
Displayed strings should be translated by __() function

Actual result (*)
Missing translation function usage in template

**Comment by lsretailomni** [comment]
Hey @utrekstur , Thanks for reporting, this has been fixed in V2.0.0. Please see the changelog here: https://github.com/lsretailomni/lsmag-two/blob/master/CHANGELOG.md#bugsfixes
