### ISSUE TITLE
Compatible with 2.4.6? 

### ISSUE THREAD

**Issue by duckchip** [lsretailomni/lsmag-two#42]
Hi guys, Will this module be compatible with Magento 2.4.6 (which will be released on March 14) ? 
Thanks in advance!

**Comment by lsretailomni** [comment]
Hi @duckchip ,

Thanks for raising the issue, the compatibility for 2.4.6 was already released in v2.3.0. Please view the changelog here: https://github.com/lsretailomni/lsmag-two/blob/master/CHANGELOG.md#230---2023-04-14
