### ISSUE TITLE
Exception in Ls\Replication\Cron\ProductCreateTask::caterItemsRemoval

### ISSUE THREAD

**Issue by bmxmiwe** [lsretailomni/lsmag-two#43]
There is uncatched exception in Ls\Replication\Cron\ProductCreateTask::caterItemsRemoval
on $this->productRepository->get($sku, true, $this->store->getId())

You are catching wrong exception. Exception instead \Exception.

### Preconditions (*)
1. Magento 2.4.3.p2 - 2.4.5
2. LS eCommerce - Magento version 1.14 - 2.2.0

### Steps to reproduce (*)
1. Run cron job with name 'repl_products' manually.
2. Have not existing sku in data table. 

### Expected result (*)

1. Exception should be catched. Logs should be in replication.log

### Actual result (*)

1. Exception - The product that was requested doesn't exist. Verify the product and try again. without any logging.

**Comment by lsretailomni** [comment]
Hi @bmxmiwe ,

Thanks for reporting this, it has been fixed in v2.3.0. Please view the change-log here: https://github.com/lsretailomni/lsmag-two/blob/master/CHANGELOG.md#230---2023-04-14
