### ISSUE TITLE
Obsolete _isScopePrivate property in blocks

### ISSUE THREAD

**Issue by bmxmiwe** [lsretailomni/lsmag-two#44]
### Preconditions (*)
1. Magento Version 2.4.3
2. LS Retail Partner name - Hagar
3. LS eCommerce - Magento version 1.18 - 2.3.0

The following table shows the private content block(s) that have the _isScopePrivate
variables configured making the block not cacheable.

app/code/Ls/Omni/Block/Cart/Coupons.php
app/code/Ls/Omni/Block/Cart/Giftcard.php
app/code/Ls/Omni/Block/Cart/Loyaltypoints.php

This property is obsolete and will not work properly.
Replace _isScopePrivate property by private content instead.

https://developer.adobe.com/commerce/php/development/cache/page/private-content/

**Comment by umarusaf902** [comment]
Hi @bmxmiwe, thanks for reporting this. This issue has already been addressed in the latest version i.e. 2.4.0.
