### ISSUE TITLE
SubtotalsAmount update in afterGetSectionData causes issues

### ISSUE THREAD

**Issue by xcom-magento** [lsretailomni/lsmag-two#45]
### Preconditions (*)
1. Magento 2.4.5
2. lsretail/lsmag-two 2.3.0

In `Ls\Omni\Plugin\Checkout\CustomerData\Cart::afterGetSectionData` the values are update in `subtotal`  and ` subtotalAmount`. Instead of setting a subtotal dependent on tax setting it just uses the grand total excluding spent loyalty point of gift card, all including tax. I'm not 100% what this exactly serves for, but this is not a proper way to do so. You would expect the totals calculators to update any totals and usage of sections.xml to match any router having to update the section data.

We are using this module in a Hyvä themes storefront and are in the process of making it compatible with Hyvä themes, but the Hyvä cart compares the subtotal in sectiondata to the subtotal in checkoutConfig.totals.subtotal. If this does not match it is a trigger to refesh the Hyvä cart. Subtotals do not match, so it just keeps on reloading the cart.

Simply commenting out the code updating the subtotalAmount and using sections.xml doesn't give me the proper results. There probably also too many caveats to start refactoring without a vast knowlegde about logic in this module. Could you please take a look a this, because it will be blocking our progress. I also have an issue where tax is substracted from the original tax amount.

We'll see if we can work around it, but updating sectiondata subtotals here seems wrong. Magento provides mechanisms to do it in other ways. The could also form problems in combination with other packages, not just Hyvä themes.

It would be very much appreciated if you can look into this.

### Steps to reproduce (*)
1. Run default Hyvä theme in you Magento install
2. Add a product to your cart
3. Go to cart page
4. Open net panel

### Expected result (*)
1. After coupons are loaded or sections update is run the is no more activity

### Actual result (*)
1. Cart, sections, coupons keep on reloading
![image](https://github.com/lsretailomni/lsmag-two/assets/50484971/a298e611-ef15-4081-a0f7-ff17700a6292)

**Comment by umarusaf902** [comment]
Hi @xcom-magento , thanks for reporting this. This issue has already been addressed and is available in the master branch and will be added in our next release.
