### ISSUE TITLE
ResetReplDiscountStatusTask Always truncate discounts on ALL stores, even if you trigger it on just one store

### ISSUE THREAD

**Issue by henriksjodahl** [lsretailomni/lsmag-two#52]
### Preconditions (*)

1. Magento ver. 2.4.2-p1
2. [Commerce Service for LS Central DB] & [LS SaaS] & [LS Central WS] LS:22.1 (23.0.6.1005108 [13659])
3. CS:2023.10.0 
4. LS Magento: 2.4
5. LS Retail Partner - Dizparc

### Steps to reproduce (*)

1. Have multiple stores configured with previously synced discounts
2. Manually trigger discount_reset in Magento Admin on a single store

### Expected result (*)

There are two options
1. Either force the ResetReplDiscountStatusTask to always run on all stores, and truncate the magento discount-tables after the loop.
2. Find another solution to only reset the discount-tables on the store running the cron.

### Actual result (*)

When running the reset on a select Store, the magento discount-tables are truncated, resulting a truncate on ALL stores, not just the one you run ResetReplDiscountStatusTask on. This is not a problem when running reset automatically, since they always run after one another, but when running reset in Admin.

**Comment by SyedWaqasNabi** [comment]
Hi, @henriksjodahl this issue has already been fixed and merged into the master branch. It will also be available in the upcoming release.
