### ISSUE TITLE
SyncPrice fails saving price on Variants of BaseUnitOfMeasure

### ISSUE THREAD

**Issue by henriksjodahl** [lsretailomni/lsmag-two#53]
### Preconditions (*)

1. Magento ver. 2.4.2-p1
2. [Commerce Service for LS Central DB] & [LS SaaS] & [LS Central WS] LS:22.1 (23.0.6.1005108 [13659])
3. CS:2023.10.0 
4. LS Magento: 2.4
5. LS Retail Partner - Dizparc

### Steps to reproduce (*)

1. Sync a Product with variants with BaseUnitOfMeasure set.
2. Create a configurable product with variants with BaseUnitOfMeasure (SKU-format: "{itemId}-{variantId}")
3. Trigger sync of price

### Expected result (*)

The price to be synced for the variant products

### Actual result (*)

There is some logical error in the conditions in SyncPrice [here](https://github.com/lsretailomni/lsmag-two/blob/10f3f048dbccf2bdcfa4a7cfc9b0a962e76d8dc9/src/Replication/Cron/SyncPrice.php#L78-L89), because if the Variant uses BaseUnitOfMeasure, the variant SKU is `{itemId}-{variantId}`, but since there is no UnitOfMeasure set on the `$replPrice` resulting in the SyncPrice-code to assume the variant sku is the format of `{itemId}-{variantId}-{sku}`

**Comment by umarusaf902** [comment]
Hi @henriksjodahl, thanks for opening reporting this issue. This has already been fixed and merged into the master branch and soon will be available in the upcoming release.
