### ISSUE TITLE
Stock sync actions without quantity changes make products disappear in storefront

### ISSUE THREAD

**Issue by xcom-magento** [lsretailomni/lsmag-two#55]
https://github.com/lsretailomni/lsmag-two/blob/465c8c980dbc19191a6f65edc573b186b3e38b5e/src/Replication/Helper/ReplicationHelper.php#L3223C17-L3223C17

On this line the cataloginventory_stock_status records for update products are removed making the products disappear in the storefront. Shouldn't be much of an issue if it is always reindexed, but when any update is trigged where the cataloginventory_stock_item record is not updated (e.g. no qty change) the changelog is not triggered and no reindex takes place making the product disappear in your store. I've tested this without this code and I don't really see why this delete statement is needed.

**Comment by SyedWaqasNabi** [comment]
Hi @xcom-magento, thanks for reporting this issue. This has already been fixed and merged into the master branch. It will also be available in the next release.
