### ISSUE TITLE
Discount missing in totals checkout/mails

### ISSUE THREAD

**Issue by xcom-magento** [lsretailomni/lsmag-two#57]
In the latest version of the LsRetail Magento module (2.7.0) the discount is missing in the totals view in the checkout and in the sales mails. We've found [this commit](https://github.com/lsretailomni/lsmag-two/commit/1b7061404034545b54a2268b96f7251dfb295a6e) where some logic is removed that applied the discountAmount to the quote item. The new totals breakdown doesn't make sense for a customer because they can't see how the order total is build up. This also applies to the sales mails.

### Preconditions (*)

1. Magento version: 2.4.7
2. LS Ecommerce Magento version: 2.7.0
3. LS Commerce version: 2024.4.1
4. LS Central version: 22.0.19.1004556 (23.1.16.587 [17599])
5. LS Retail partner: TCOG

### Steps to reproduce (*)
1. Add a product to the cart that has a discount in LS. 
2. Go to the checkout and check the totals.

### Expected result (*)
1. The applied discount is visible in the totals overview.
_Screenshot below is from production environment with older version of the LsRetail module_
![lsretail_correct](https://github.com/lsretailomni/lsmag-two/assets/50484971/ff320a26-dab8-4c55-bfc2-d974609d1a99)

### Actual result (*)
1. The applied discount isn't visible anymore since the latest version.
![lsretail_wrong](https://github.com/lsretailomni/lsmag-two/assets/50484971/23116525-9216-4457-a263-b0b80461ca1e)

**Comment by umarusaf902** [comment]
Hi @xcom-magento, thanks for reporting the issue. We are looking into it. In the mean time can you confirm if this discount is a discount offer, mix and match offer or a coupon offer ?

**Comment by xcom-magento** [comment]
Hi @umarusaf902, the OneListCalculate response is:
```
<a:OrderDiscountLine>
    <Id xmlns="http://lsretail.com/LSOmniService/Base/2017"/>
    <a:Description>van 325,00 voor 229,00</a:Description>
    <a:DiscountAmount>96.00</a:DiscountAmount>
    <a:DiscountPercent>29.54</a:DiscountPercent>
    <a:DiscountType>PeriodicDisc</a:DiscountType>
    <a:LineNumber>10000</a:LineNumber>
    <a:No>10000</a:No>
    <a:OfferNumber>PR-0025</a:OfferNumber>
    <a:OrderId/>
    <a:PeriodicDiscGroup>PR-0025</a:PeriodicDiscGroup>
    <a:PeriodicDiscType>DiscOffer</a:PeriodicDiscType>
</a:OrderDiscountLine>
```
The `PeriodDiscType` is DiscOffer, so i think a discount offer.

**Comment by umarusaf902** [comment]
Hi @xcom-magento, thanks for providing more details. FYI, we have managed to fix the issue and the code has already made its way into master branch and it will be available in the next release.
