### ISSUE TITLE
Magento 2.3 Compatibility?

### ISSUE THREAD

**Issue by jwGeorge** [lsretailomni/lsmag-two#6]
Hi Team,

We are in the process of deploying a new Magento 2 site and our developers have asked if this project is v2.3 compatible as their are apparently quite a few structural changes between 2.2 and 2.3.

Thanks!
George

**Comment by jwGeorge** [comment]
@zeeshanlsretail @lsretailomni - Hi Team, Any response for this?

**Comment by sudhanshu-bajaj** [comment]
Sorry for late reply. Yes its compatible @jwGeorge. Thanks.
